version: '2'

services:
  ejabberd:
    build: .
    # build from Dockerfile
    dockerfile: Dockerfile
    ports:
     - "5222:5222"
     - "5443:5443"
     - "5280:5280"
    volumes:
     - ./conf/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml 
  